### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by shanetorres** [balena-io-modules/drivelist#357] opened 2019-11-26 18:10 UTC
Trying to use drivelist in a NW.js project. 

Using drivelist version 8.0.9 and NW.js version 0.35.4
I keep getting the following error:
![image](https://user-images.githubusercontent.com/29207194/69660132-a2518880-104d-11ea-8de2-1f4c368e09ba.png)

This is the code I am using
`const drivelist = require('drivelist');`
`drivelist.list().then(`
`    drives => console.log(drives),`
`    err => console.error(err)`
 ` )`

Anyone have any ideas? I've tried a lot of different things like installing nw-gyp and configuring NW.js to use native node modules but nothing is working. I really need this module to work correctly for my project. Any help is much appreciated.

Edit: I'm on windows 10 64 bit

**Comment by lurch** [comment] 2019-12-02 12:02
Duplicate of #226 ?

**Closed** 2019-12-02 16:58 UTC
